### PR TITLE
it's a start. congrats! =D

### PR DESCRIPTION
**Pull request by chrisgbaker**
While it IS my favorite part of standup to watch @woolsox furiously lower the volume, I figured this might make it a bit easier. 

Untested however; I don't have maestro setup locally, and not the best at `bash`. So, tear it apart!

### CODE REVIEW

**Comment by dkniffin** [comment]
I love this idea, but not 100% sold on how it's implemented here. `spotify.sh` is our copy of [shpotify](https://github.com/hnarayanan/shpotify), so I don't want to make changes directly to that if we can avoid it. 

The two options I would be okay with are:
1. (preferred) Open a PR over there, and if they accept it, then we can pull it back in here
2. Implement this in the ruby layer instead, so it'd become `/maestro fadeout` and that would repeatedly run `spotify.sh vol down` until it's at 0.

**Comment by chrisgbaker** [comment]
@dkniffin https://github.com/hnarayanan/shpotify/pull/121 We'll see if he wants this merged as well

**Comment by hnarayanan** [comment]
Let me try to understand what is going on. The code change seems light enough, but once I understand what you're trying to do better I will merge it.

**Comment by dkniffin** [comment]
@hnarayanan Awesome, thank you.

Side-note: Any chance we could have maestro mentioned somewhere in the shpotify readme as a "this thing uses shpotify, go check it out" kind of thing?

**Comment by hnarayanan** [comment]
Even better, if you could come up with a list of handful of projects that embed shpotify (I know oh-my-zsh is one of them), then I will make a dedicated section of the README to apps that build on it.

**Comment by dkniffin** [comment]
@hnarayanan https://github.com/hnarayanan/shpotify/pull/122 The only one I could find is the oh-my-zsh plugin

**Pull request merged**
